import type { Metadata } from "next";
import localFont from "next/font/local";
import ClientLayout from "@/components/ClientLayout"; // Donde manejamos las cosas del cliente
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Gymmy",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png", // Agregamos el ícono para Apple
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link className="rounded" rel="icon" href="favicon.ico" />
      <body className="bg-gray-400 min-h-screen">
        <ClientLayout>{children}</ClientLayout> {/* Manejamos el cliente aquí */}
      </body>
    </html>
  );
}
